personal:
  name: "kepennar"
  email: "{{ .chezmoi.config.data.personal.email | required }}"
  github_username: "{{ .chezmoi.config.data.personal.username | required }}"

development:
  editor: "code"
  shell: "zsh"
  terminal: "terminator"

fonts:
  terminal: "CaskaydiaCove Nerd Font"
  editor: "CaskaydiaCove Nerd Font"

colors:
  theme: "dark"

paths:
  workspace: "~/workspace"
  projects: "~/projects"

tools:
  node_version: "lts"
  python_version: "3.11"

os:
  is_arch: "{{ .chezmoi.config.data.os.is_arch | required }}"
  is_manjaro: "{{ .chezmoi.config.data.os.is_manjaro | required }}"
  is_ubuntu: "{{ .chezmoi.config.data.os.is_ubuntu | required }}"
