personal:
  name: "kepennar"

machine:
  role: "desktop" # desktop or server
  desktop: "kde" # gnome, kde, sway, none

features:
  gui: true
  docker: true
  kubernetes: false
  cloud_sdk: false
  install_fonts: true
  flatpak_apps: false
  work_profile: false
  install_desktop_apps: true
  install_dev_tools: true

development:
  editor: "code"
  shell: "zsh"
  terminal: "ghostty"

fonts:
  terminal: "CaskaydiaCove Nerd Font"
  editor: "CaskaydiaCove Nerd Font"
  nerd_font_version: "v3.1.1"

colors:
  theme: "dark"

paths:
  workspace: "~/workspace"
  projects: "~/projects"

tools:
  node_version: "lts"
  python_version: "3.11"
